{% set version = "1.2.0" %}

package:
  name: wrf-python
  version: {{ version }}

source:
  fn: wrf-python-{{ version }}.tar.gz
  url: https://github.com/NCAR/wrf-python/archive/{{ version }}.tar.gz
  sha256: 8b6b57769d4c3d4468d44ad2223232b27d93325838ebb5cfdee6d565044f294b

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
  host:
    - setuptools
    - python
    - numpy  # [unix]
    - numpy 1.14.*  # [win]
    - wrapt
  run:
    - setuptools
    - numpy  # [unix]
    - numpy >=1.14  # [win]
    - python
    - wrapt
    - xarray

test:
  requires:
    - setuptools
    - netcdf4
    - xarray
  source_files:
    - test/ci_tests
  imports:
    - wrf
  commands:
    - cd test/ci_tests && python utests.py

about:
  home: https://github.com/NCAR/wrf-python
  license: "UCAR"
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "Diagnostic and interpolation routines for WRF-ARW data."

extra:
  recipe-maintainers:
    - bladwig1
    - marylhaley
    - david-ian-brown
    - khallock
