travis:
  secure:
    BINSTAR_TOKEN: ps/CeCNZlHXZ48mVgs6tOQc0qTSsMW/YKdFn7VoTwus/VKLmVIxTSHNp4BuBtOFvzw5L7isxAd3csasBsKQDvWgUAphDxAdRp7YuukTsZ2z9Im4fEt5AVY3xqPrbWUAkm8nwuat9EH6BDSbM+q42OOta37KeesSOkhG0enpj8Q5m5/Pjm733ug5Ec6jxR845OyHozQVmb/j0iMKVkEGP+n6/0Q9t9EjffLx+VgezM9KPPFEq4EBCLsqTLJOhnwSZ3k6hp5X6ep3AULApsvNywSx2qRw6uN4+FjcykU714DYiEYpF89qBoUuJ/xiwN8aGIXtd/t8u+6IKH1ZiglCzIyUxI1yuR5t8yAxLz5vW9rwTMVG2H2UY/OkwfQjdcToBui/SHn1VhkFJZpw3ehG104LjzoNikxoxqZnCmc1hUh7HBK6yCarAFxns7cE3aIoF1UgWH+jTVY0j16FRi0f24UbB+4ACp6Lblc/BZM02QrapwFZig7jw5n7p+DPwBv50QiLs1WQ60FBo8EF5CnMpSA3vjG49UBjG6ebK1MREcX1FN09VxhMaSFuY8MF61p9psobXDgV6YyG/0oRBjJ62aA62Nx79TeV4UvkZfdk30YAcf6nGkuAJiFDUd7vduRiGONlkYblHhOUGyplyHqfdR+BcpY+CzRAY0HsSKCaePJE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
