travis:
  secure:
    BINSTAR_TOKEN: rAr1lNb0sS0k+zdI8DWDgSVRGPUOrqv4fhL9pfJQDzLMn+BA2D6WsXV4bhnqWdMNJ4sAAh7iQ1JvV2jZmcZZJ4vLr6uJxuIu9Ys8dwP7UuNLtKJ93RUUGX9LOBrOVhRNSIlLHwveXh/hrcWVWcqzJdPM1Adu94wDjB+Isru1gkVn7D/meKDCl5cAO/4hXHGKHzo7IgukXWOdZUMuxb355MlK6AHSncmB9ytUmEy4fLeidw7rD8r6JEJAo+qFfGFvty3rwLeL1VKkOzgMMXycmlRffM/uMPVcuh4lMXHNR9Gd0Eu3dXuJpDotiDpyGU0PVQLa4jSxRcGH0uNe9xqRAeTAdT8jQgfs426wSuh20VhSsP6Mum0ZhMgAIcYd/9rf2x1y2KE1d8nk7irpcoBGlSCvcUUuMduAQqqYKAfCTmKgNIW35bXT+P02WtelDSS7yyv4R6pwyc+kEgva0OK8Hu5Zok1VoO/4oeTrAjmYGohEhfsRTJUnDulnATltkSoL62FEvuiumrXPb27Izr0gL2mCEToeGe/ppgfI3t1WOR0LE5gjLbpjkFCy9fBvd00FVv0aKjiSjzRUNDahgd5vlxATeF056YEcUOrZKHki/K51otRy+xILIvhOHUy4j69FLIOrY3aOY79CyO/RwaMmZ4NOHsmn0L/mdzPJCzb8Udc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
